### ISSUE TITLE
Suggested updates

### ISSUE THREAD

**Issue by gueyenono** [aschersleben/cointReg#1]
When trying to access the coefficients of a model estimated with the "cointReg" function, it is conveniently possible to use the `object$beta` attribute. However, `object$beta` is less convenient than other attributes, say `object$sd.theta` for a few reasons:

(i) when the model is estimated with a deterministic component (e.g. a constant term), even though the coefficient of the deterministic component is appropriately printed in the model summary, `object$beta` does not contain it. 

(ii) `object$beta` is an unnamed vector just like `object$sd.theta` for example.

(iii) It would be very convenient to add an attribute to "cointReg" objects that would provide the data.frame (I believe) printed in the model summary - the one with the coefficients, standard errors, t-values and p-values.

**Comment by aschersleben** [comment]
Thanks for your feedback and your suggestions.

(i) `object$beta` just contains the regressor coefficients, that's right. The deterministic coefficients are stored in `object$delta` -- and both together can be found in `object$theta`. This is also described on the help pages, but I agree that this is not really clear yet.
I hope these changes help: 7c07e1574aa899421a5dd6b6ef245a4ed53c5739

(ii) `object$beta` shouldn't be unnamed, can you give an example?

``` r
set.seed(1909)
x1 <- cumsum(rnorm(100, mean = 0.05, sd = 0.1))
x2 <- cumsum(rnorm(100, sd = 0.1)) + 1
x3 <- cumsum(rnorm(100, sd = 0.2)) + 2
x <- cbind(x1, x2, x3)
y <- x1 + x2 + x3 + rnorm(100, sd = 0.2) + 1
object <- cointRegFM(x, y, deter = rep(1, 100))
object$beta
##        x1        x2        x3 
## 0.9758474 0.9139058 0.9550826 
```

The coefficient vectors should have names as long as `x` is a _named_ vector / matrix / data.frame.

(iii) Good idea, I will add it with the next update.
See f44a257da8aab91d844deb997c8c5013f2f19184.

**Comment by gueyenono** [comment]
Thank you very much for your prompt response.

(i) I really appreciate the info. I didn't know about it. Actually, I have been using the package prior to it being on CRAN and I don't know whether the help was as detailed as it is now, but I remember looking.

(ii) If you rerun your code with `cointRegD`, then `object$beta` is an unnamed vector:

(iii) I am glad you like the idea.
