### ISSUE TITLE
Suggestion: use lm-like formula interface and with weights enabled

### ISSUE THREAD

**Issue by Fifis** [aschersleben/cointReg#3]
I have been using this package for quite some time, and, as amazing as it is, a lot of work has to be done manually after the estimation.

Estimation via formulae or with weights have been standard in R packages. E.g. if one desires robust IRLS estimates instead of simple OLS ones, one just swaps `lm(y ~ x1 + x2)` with `MASS::rlm(y ~ x1 + x2)`. Likewise, observation weights can be supplied and used in the model matrix construction. As of now, no such facilities are provided. As a consequence, it is impossible to apply any of the standard linear-model functionality extension to `cointReg` objects. No `sandwich`, `MASS`, `car`, `restriktor` etc. Even `stats::coef` returns null, although the model has $theta that should probably be returned (because `$varmat` describes it).

Are there any plans to add the formula-like interface, or is this package frozen?

**Comment by Fifis** [comment]
P.S. The function `getModD` exists (not exported from the namespace), but it is applied directly to the matrices `y` and `x`, with no way of adding a formula interface.

**Comment by aschersleben** [comment]
Hi,
as my research focus changed a lot in the last years, I won't do any changes here in the near future. If you are motivated and able to implement the suggested changes, please feel free to fork the repository and provide a pull request!
I'm sorry that I cannot give you any better answer at the moment.
Philipp
